### ISSUE TITLE
Information Query: What is the hash, and how can I get mine??

### ISSUE THREAD

**Issue by confusedeinstein** [henrytirla/DEX-Essential-Trading-Scripts#1]
Hello, 
I was going through you **CopyTrade-IrrespectiveOfRouter.py** . I am unable to understand what is this hash
```
if logs['address'] == WETH and alchemy.to_hex(logs['topics'][0]) == "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef":
```
also this hash

```
elif logs['address'] != WETH:
                if alchemy.to_hex(
                        logs['topics'][0]) == "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925":
```

can you help me out a bit over here?

**Comment by henrytirla** [comment]
Hello, the hash values you provided are standard function signatures commonly used in Ethereum transactions and logs. They are not specific to any particular user or application. For instance, the hash '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' is associated with the 'Transfer' function, commonly used in ERC-20 token contracts for transferring tokens between addresses. On the other hand, the hash '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925' represents the 'Approval' function, often used in the same context for approving the transfer of tokens. These standard function signatures play a crucial role in interpreting and understanding the actions encoded in Ethereum transactions and logs across the entire network. I have added screenshots for more context 
<img width="1109" alt="Transfer" src="https://github.com/henrytirla/Decentralized-Exchange-Trading-Scripts/assets/18648533/d81261ea-697e-44c8-82b5-a935a3d9db8b">

<img width="1359" alt="Approve" src="https://github.com/henrytirla/Decentralized-Exchange-Trading-Scripts/assets/18648533/6b38bc04-4c1f-4c1b-a269-97f251d2ecfa">
