### ISSUE TITLE
This doesnt seem to capture all new LP's

### ISSUE THREAD

**Issue by philashworth** [henrytirla/DEX-Essential-Trading-Scripts#10]
Ive been running this over several days and it doesnt appear to capture all new pools. 
An example today LP pair 5X4XmtsQguE6jmHXHwvWYwm4HdRYLureUYUw4VXmTb3Y which is a new token GnZmtv9eJFgxcVmKCT3HanANnPgBpjmfiGK6VpwDy4S
it didnt come though. 
Im seeing multiple of these a day, is there another log instruction I should be looking for?

**Comment by henrytirla** [comment]
The code in the repo is not optimize. I will update it soon. Best regards
