### ISSUE TITLE
how to buy and sell in pump.fun?

### ISSUE THREAD

**Issue by cvbdfgfdg** [henrytirla/DEX-Essential-Trading-Scripts#11]
How to trade Solana’s tokens? The tokens issued on the pump.fun website are not in the raydium pool. How can I trade them through code?

**Comment by Assassin1024** [comment]
你好朋友！！机遇不等人，有兴趣的可以加我QQ 2580271695   了解一下也无防的！！

**Comment by henrytirla** [comment]
Your question is not related to any code in this repo.
