### ISSUE TITLE
How to fetch_pool_keys faster ? 

### ISSUE THREAD

**Issue by hello7623** [henrytirla/DEX-Essential-Trading-Scripts#6]
Hi, A very very good jobs !!
I have some wonder about you pull pool keys via fetch_pool_keys, some times. it need to get this info from https://api.raydium.io/v2/sdk/liquidity/mainnet.json. 
when you detect a new pool. can get this info from `def process_messages` in ?, make it more faster ?

**Comment by henrytirla** [comment]
Yes this is feasible

**Comment by hello7623** [comment]
Would you make a tutoral about how to do it ? very very thanks for that !!!

**Comment by henrytirla** [comment]
Yes. It will be Opensource in this repository. And I will write an article on medium

**Comment by hello7623** [comment]
Thanks！ 
best wishes to you！

**Comment by henrytirla** [comment]
Same to you. Happy Sunday I will be uploading the code today.
